## Data Prepration

1. Import Libraries

In [1]:
import pandas as pd 
import numpy as np

2. Exploratory Data Analysis (EDA) ✅

In [2]:
df = pd.read_csv('DelayedFlights.csv/DelayedFlights.csv')
df.head()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [3]:
df.isnull().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB

In [5]:
df.describe()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,1.936758e+06,1936758.0,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.929648e+06,1.936758e+06,1.936758e+06,...,1.936758e+06,1.929648e+06,1.936303e+06,1.936758e+06,1.936758e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06
mean,3.341651e+06,2008.0,6.111106e+00,1.575347e+01,3.984827e+00,1.518534e+03,1.467473e+03,1.610141e+03,1.634225e+03,2.184263e+03,...,7.656862e+02,6.812975e+00,1.823220e+01,3.268348e-04,4.003598e-03,1.917940e+01,3.703571e+00,1.502164e+01,9.013714e-02,2.529647e+01
std,2.066065e+06,0.0,3.482546e+00,8.776272e+00,1.995966e+00,4.504853e+02,4.247668e+02,5.481781e+02,4.646347e+02,1.944702e+03,...,5.744797e+02,5.273595e+00,1.433853e+01,1.807562e-02,6.314722e-02,4.354621e+01,2.149290e+01,3.383305e+01,2.022714e+00,4.205486e+01
min,0.000000e+00,2008.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,...,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.517452e+06,2008.0,3.000000e+00,8.000000e+00,2.000000e+00,1.203000e+03,1.135000e+03,1.316000e+03,1.325000e+03,6.100000e+02,...,3.380000e+02,4.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,3.242558e+06,2008.0,6.000000e+00,1.600000e+01,4.000000e+00,1.545000e+03,1.510000e+03,1.715000e+03,1.705000e+03,1.543000e+03,...,6.060000e+02,6.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,8.000000e+00
75%,4.972467e+06,2008.0,9.000000e+00,2.300000e+01,6.000000e+00,1.900000e+03,1.815000e+03,2.030000e+03,2.014000e+03,3.422000e+03,...,9.980000e+02,8.000000e+00,2.100000e+01,0.000000e+00,0.000000e+00,2.100000e+01,0.000000e+00,1.500000e+01,0.000000e+00,3.300000e+01
max,7.009727e+06,2008.0,1.200000e+01,3.100000e+01,7.000000e+00,2.400000e+03,2.359000e+03,2.400000e+03,2.400000e+03,9.742000e+03,...,4.962000e+03,2.400000e+02,4.220000e+02,1.000000e+00,1.000000e+00,2.436000e+03,1.352000e+03,1.357000e+03,3.920000e+02,1.316000e+03

3. Data Cleaning

In [6]:
# Drop rows with missing values in specific columns
df.dropna(subset=['ActualElapsedTime', 'AirTime', 'ArrDelay', 'ArrTime', 'TaxiIn'], inplace=True)

In [7]:
df.isnull().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                   0
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   3
ActualElapsedTime         0
CRSElapsedTime            0
AirTime                   0
ArrDelay                  0
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                    0
TaxiOut                   0
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         680883
WeatherDelay         680883
NASDelay             680883
SecurityDelay        680883
LateAircraftDelay    680883
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1928371 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 456.1+ MB

In [9]:
# Create a date column from Year, Month, and DayofMonth
df['Date'] = pd.to_datetime(df[['Year', 'Month', 'DayofMonth']].rename(columns={'DayofMonth': 'day', 'Month': 'month', 'Year': 'year'}))
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1928371 entries, 0 to 1936757
Data columns (total 31 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
 30  Date               datetime64[ns]
dtypes: datetime64[ns](1), float64(14), int64(11), object(5)
memory usage: 470.8+ MB

# Dim Airport

In [10]:
# Keep Origin and Dest as they are and remove duplicates
dim_airport = df[['Origin', 'Dest']].drop_duplicates().reset_index(drop=True)

# Create surrogate key by combining Origin and Dest
dim_airport['Airport_ID'] = (dim_airport['Origin'] + '-' + dim_airport['Dest'])

# Save to CSV
dim_airport.to_csv('dim_airport.csv', index=False)

print(dim_airport.head())
print(dim_airport.shape)

  Origin Dest Airport_ID
0    IAD  TPA    IAD-TPA
1    IND  BWI    IND-BWI
2    IND  JAX    IND-JAX
3    IND  LAS    IND-LAS
4    IND  MCO    IND-MCO
(5127, 3)

# Dim Airline

In [12]:
# Keep the 4 columns and remove duplicates
dim_airline = df[['UniqueCarrier', 'FlightNum', 'TailNum']].drop_duplicates().reset_index(drop=True)

# Cast to string and create surrogate key by combining the 3 columns
dim_airline['Airline_ID'] = (dim_airline['UniqueCarrier'].astype(str) + '-' + 
                              dim_airline['FlightNum'].astype(str) + '-' + 
                              dim_airline['TailNum'].astype(str))

# Save to CSV
dim_airline.to_csv('dim_airline.csv', index=False)

print(dim_airline.head())
print(dim_airline.shape)

  UniqueCarrier  FlightNum TailNum      Airline_ID
0            WN        335  N712SW   WN-335-N712SW
1            WN       3231  N772SW  WN-3231-N772SW
2            WN        448  N428WN   WN-448-N428WN
3            WN       3920  N464WN  WN-3920-N464WN
4            WN        378  N726SW   WN-378-N726SW
(1128834, 4)

# Dim Date

In [13]:
# Keep the 4 columns and remove duplicates
dim_date = df[['Year', 'Month', 'DayofMonth', 'DayOfWeek']].drop_duplicates().reset_index(drop=True)

# Create Date column
dim_date['Date'] = pd.to_datetime(dict(year=dim_date['Year'], 
                                        month=dim_date['Month'], 
                                        day=dim_date['DayofMonth']))

# Create surrogate key by combining the 3 columns
dim_date['Date_ID'] = (dim_date['Year'].astype(str) + '-' + 
                        dim_date['Month'].astype(str) + '-' + 
                        dim_date['DayofMonth'].astype(str))

# Save to CSV
dim_date.to_csv('dim_date.csv', index=False)

print(dim_date.head())
print(dim_date.shape)

   Year  Month  DayofMonth  DayOfWeek       Date   Date_ID
0  2008      1           3          4 2008-01-03  2008-1-3
1  2008      1           4          5 2008-01-04  2008-1-4
2  2008      1           5          6 2008-01-05  2008-1-5
3  2008      1           6          7 2008-01-06  2008-1-6
4  2008      1           7          1 2008-01-07  2008-1-7
(366, 6)

# Fact Flights

In [20]:
fact_flights = df.drop(columns=['Unnamed: 0',
                                 'Year', 'Month', 'DayofMonth', 'DayOfWeek',
                                 'UniqueCarrier', 'FlightNum', 'TailNum',
                                 'Origin', 'Dest']).copy()

fact_flights['Date_ID'] = (df['Year'].astype(str) + '-' + 
                            df['Month'].astype(str) + '-' + 
                            df['DayofMonth'].astype(str))

fact_flights['Airport_ID'] = (df['Origin'].astype(str) + '-' + 
                               df['Dest'].astype(str))

fact_flights['Airline_ID'] = (df['UniqueCarrier'].astype(str) + '-' + 
                               df['FlightNum'].astype(str) + '-' + 
                               df['TailNum'].astype(str))

fact_flights.fillna(0, inplace=True)

# Optimize Data Types
fact_flights['DepTime'] = fact_flights['DepTime'].astype('int16')
fact_flights['ArrTime'] = fact_flights['ArrTime'].astype('int16')
fact_flights['CRSDepTime'] = fact_flights['CRSDepTime'].astype('int16')
fact_flights['CRSArrTime'] = fact_flights['CRSArrTime'].astype('int16')
fact_flights['CRSElapsedTime'] = fact_flights['CRSElapsedTime'].astype('int16')
fact_flights['DepDelay'] = fact_flights['DepDelay'].astype('int16')
fact_flights['ArrDelay'] = fact_flights['ArrDelay'].astype('int16')
fact_flights['Distance'] = fact_flights['Distance'].astype('int16')
fact_flights['TaxiIn'] = fact_flights['TaxiIn'].astype('int16')
fact_flights['TaxiOut'] = fact_flights['TaxiOut'].astype('int16')
fact_flights['ActualElapsedTime'] = fact_flights['ActualElapsedTime'].astype('int16')
fact_flights['AirTime'] = fact_flights['AirTime'].astype('int16')
fact_flights['Cancelled'] = fact_flights['Cancelled'].astype('int8')
fact_flights['Diverted'] = fact_flights['Diverted'].astype('int8')
fact_flights['CarrierDelay'] = fact_flights['CarrierDelay'].astype('int16')
fact_flights['WeatherDelay'] = fact_flights['WeatherDelay'].astype('int16')
fact_flights['NASDelay'] = fact_flights['NASDelay'].astype('int16')
fact_flights['SecurityDelay'] = fact_flights['SecurityDelay'].astype('int16')
fact_flights['LateAircraftDelay'] = fact_flights['LateAircraftDelay'].astype('int16')
fact_flights['CancellationCode'] = fact_flights['CancellationCode'].astype(str)

fact_flights.to_csv('fact_flights.csv', index=False)

print(fact_flights.columns.tolist())
print(fact_flights.shape)

['DepTime', 'CRSDepTime', 'ArrTime', 'CRSArrTime', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay', 'DepDelay', 'Distance', 'TaxiIn', 'TaxiOut', 'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay', 'Date', 'Date_ID', 'Airport_ID', 'Airline_ID']
(1928371, 24)